virus0check/hash/urls.py
from django.conf.urls.static import static
from django.urls import path

from virus0check import settings
from .views import *
from . import views

#urlpatterns = [
#    path('', index),
#    path('result/', result),
#]

urlpatterns = [
    path('', views.file_upload_view, name='file_upload_view'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

virus0check/virus0check/urls.py
from django.contrib import admin
from django.urls import path

from hash.views import *
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hash.urls')),
]

virus0check/hash/models.py
from django.db import models


class MalwareHash(models.Model):
    hash = models.CharField(max_length=128)

    
def __str__(self):
    return self.title

virus0check/hash/forms.py
from django import forms


class FileUploadForm(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput())

virus0check/hash/views.py
from .utils.uploadfunc import file_upload_func


def file_upload_view(request):
    return file_upload_func(request)

virus0check/hash/templates/virus0check/result.html
<head>
    <link rel="stylesheet" href="static/css/styles.css">
</head>
<body>
    <div id="result-block">
        <div class="result">{{ result }}</div>
        <div class="file_info">{{ file_info|linebreaks }}</div>
        <div class="button_ref">
            <a href="{% url 'file_upload_view' %}">Назад</a>
        </div>
    </div>
</body>

virus0check/hash/templates/virus0check/upload.html
<head>
    <link rel="stylesheet" href="static/css/styles.css">
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
    <div id="upload-block">
        <img width="1200" src="static/images/virus.png" alt="Логотип" />
        <p class="text">Анализируйте файлы для обнаружение вредоносных программ</p>
        {% csrf_token %}
        <div class="input__wrapper">
            <div class="spryatat">
                {{ form.as_p }}
            </div>
            <label for="id_file" class="input__file-button">
                <span class="input__file-icon-wrapper"><img class="input__file-icon" src="static/images/download.png" alt="Выбрать файл" width="25"></span>
                <span class="input__file-button-text">Выберите файл</span>
            </label>
        </div>
        <button id="button-check" type="submit">Проверить файл</button>
    </div>
    </form>
</body>